### PR TITLE
fix & update zh translation

### PR DESCRIPTION
**Pull request by Emphasia**
based on the Base & existing strings files.

### CODE REVIEW

**Comment by Emphasia** [comment]
please add those?

**Comment by abnerlee** [comment]
Files under help will not be translated by now, since their `*.md` file is in English, so it does not make sense that after user click a Chinese menu item, but an English manual popup.

**Comment by abnerlee** [comment]
Thanks for the Fix. Basically the translation is improved.

But I will pick your translation and close this one, since modify by me will be quicker and easier than comment on this MR, and then let you fix it 😂 

I will post my MR link when it is done.

**Comment by Emphasia** [comment]
But there are instructions that lead to these strings which have already been translated, I'm afraid this may seem confusing.
e.g. https://github.com/typora/Typora-i18n/blob/ea0dd0d8594cdf0e94ae2ac165a9598bcba6fcf3/Base.lproj/Panel.strings#L98
(btw, here is "use" and the UI is "Use".)

Personally, I think them translated seems more comfortable even if the *.md files are still in English.
😂

**Comment by Emphasia** [comment]
> But I will pick your translation and close this one, since modify by me will be quicker and easier than comment on this MR, and then let you fix it. I will post my MR link when it is done.

Sorry, but I don't really understand what you mean..😂

**Comment by Emphasia** [comment]
no no no, I wasn't add this commit...

**Comment by abnerlee** [comment]
> Sorry, but I don't really understand what you mean.

I mean I will pick some of your translations and modify based on my understanding, and then merge it. 

Most translation is good to me, but some I need to change, so I will change on my own without asking you for doing that.

**Pull request closed without merging**
