### PR TITLE
Update zh-Hans strings

### PR DESCRIPTION
**Pull request by leostudiooo**
Changes:
- Replace words  (e.g. “拷贝”) with more proper and native words (e.g. “复制”).
- Fit [_Chinese Copywriting Guidelines_ 中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines) to unify the styles (by adding spaces between Latin characters/numbers and Chinese characters).
- Replace untranslated strings (e.g. `zh-Hans.lproj/Panel.strings`, line 19: "_Quick Start_" to “新手教程” (from `zh-Hans.lproj/Welcome.strings`, line 43: `"Quick Start" = "新手教程";`)).

### CODE REVIEW

**Comment by Yexiaoxing** [comment]
According to localize-mainmenu, copy is translated to "拷贝" (Ref: https://github.com/martnst/localize-mainmenu/blob/master/languages/zh-CN.json); also macOS itself is using 拷贝 (Ref: https://support.apple.com/zh-cn/HT201236).

**Comment by leostudiooo** [comment]
> According to localize-mainmenu, `copy` is translated to "拷贝" (Ref: https://github.com/martnst/localize-mainmenu/blob/master/languages/zh-CN.json); also macOS is using 拷贝 (Ref: https://support.apple.com/zh-cn/HT201236). As we cannot do per-OS translation, changing to “复制” might be okay but not sure.

Yes, it is pretty confusing because Windows uses “复制”.  
image
Then let's just let it be there and make no change. 

What about the other parts?

**Comment by Yexiaoxing** [comment]
Others LGTM, but I cannot decide it lol:)
Different wordings between OS could be a challenge for translation.

**Comment by leostudiooo** [comment]
> Others LGTM, but I cannot decide it lol:) Different wordings between OS could be a challenge for translation.

Thanks though:smile:

**Pull request closed without merging**
